# Generated by Django 4.2.27 on 2026-01-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0029_auto_20251009_1148"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitorpolicy",
            name="detects_config",
            field=models.JSONField(default=dict, verbose_name="触发配置"),
        ),
        migrations.AddField(
            model_name="monitorpolicy",
            name="no_data_config",
            field=models.JSONField(default=dict, verbose_name="数据信息"),
        ),
    ]
